###############################################################################
# MCP Mimir — PROD Environment Overlay
#
# Namespace:  sample-prod
# Key Vault:  sample-prod-eu-kv-01
# Hostname:   sample-metrics-prod-01.albertsons.com
# Replicas:   3
# Extras:     NetworkPolicy, tighter PDB
###############################################################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-prod

labels:
  - pairs:
      environment: prod
    includeSelectors: false

resources:
  - ../../base
  - networkpolicy.yaml

patches:
  - path: deployment-patch.yaml
  - path: virtualservice-patch.yaml
  - path: azure-keyvault-patch.yaml
  - path: configmap-patch.yaml
  - path: pdb-patch.yaml
