apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: mcp-mimir-service-account-token
spec:
  vault:
    name: sample-perf-eu-kv-01
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: mcp-mimir-tls-ca
spec:
  vault:
    name: sample-perf-eu-kv-01
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: mcp-mimir-tls-cert
spec:
  vault:
    name: sample-perf-eu-kv-01
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: mcp-mimir-tls-key
spec:
  vault:
    name: sample-perf-eu-kv-01
