apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-prometheus-perf

labels:
  - pairs:
      app.kubernetes.io/instance: perf
      environment: perf
    includeSelectors: false

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
  - path: hpa-patch.yaml

configMapGenerator:
  - name: mcp-prometheus-config
    behavior: merge
    literals:
      - PROMETHEUS_URL=http://mimir-gateway.mimir-perf.svc.cluster.local:8080/prometheus
      - PROMETHEUS_ORGID=perf-tenant
