apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources — all environments share these
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - azure-keyvault-secrets.yaml
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
  - pdb.yaml
