apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

configMapGenerator:
  - name: mcp-prometheus-config
    literals:
      - PROMETHEUS_URL=http://prometheus.monitoring.svc.cluster.local:9090
      - PROMETHEUS_ORGID=
      - TRANSPORT=sse
      - HTTP_ADDR=:8080
      - METRICS_ADDR=:9091

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
