apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcp-prometheus
spec:
  rules:
    - host: mcp-prometheus-dev.aks.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mcp-prometheus
                port:
                  name: http-mcp
